version: "3.4"

services:
  turquoise-scheduler:
    image: turquoise-scheduler-test
    build:
      target: test
      context: ../
      dockerfile: Turquoise.Scheduler/Dockerfile-test
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
