version: "3.4"

services:
  turquoise-scheduler:
    image: mmercan/turquoise-scheduler:${TAGVersion}-prod-linux
    build:
      target: final
      context: ../
      dockerfile: Turquoise.Scheduler/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    # ports:
    #   - "5005:80"
