FROM mmercan/sentinel-sonarqube-dotnet30-sdk AS test
ARG buildtime_APPID
ARG buildtime_APPSECRET
ARG buildtime_ADID
ARG buildtime_SONARKEY
ENV ASPNETCORE_URLS=http://+:80
ENV PROJECT=Turquoise.Api.HealthMonitoring
ENV VERSION=1.0
ENV SONARKEY=$buildtime_SONARKEY
ENV APPID=$buildtime_APPID
ENV APPSECRET=$buildtime_APPSECRET
ENV ADID=$buildtime_ADID
ENV SentinelConnection="Server=52.247.221.7;Database=sentinel;User Id=sa;Password=MySentP@ssw0rd;"
ENV SONAR_HOST=https://sonarcloud.io

WORKDIR /src
COPY Turquoise.Api.HealthMonitoring/Turquoise.Api.HealthMonitoring.csproj Turquoise.Api.HealthMonitoring/
RUN dotnet restore Turquoise.Api.HealthMonitoring/Turquoise.Api.HealthMonitoring.csproj
COPY . .
RUN dotnet sonarscanner begin /k:$PROJECT /v:$VERSION /d:sonar.host.url=$SONAR_HOST /o:mmercan-github /d:sonar.login=$SONARKEY  /d:sonar.cs.opencover.reportsPaths="/TestResults/coverage.opencover.xml" /d:sonar.exclusions="**bootstrap.css, **bootstrap-reboot.css, **bootstrap.js, **/wwwroot/**, **Sentinel.Empty.Tests" /d:sonar.coverage.exclusions="**Tests*.cs, **.js," /d:sonar.cs.vstest.reportsPaths="/TestResults/*.trx"
RUN dotnet build ./Turquoise.Api.HealthMonitoring/Turquoise.Api.HealthMonitoring.sln

RUN dotnet test ./Turquoise.Api.HealthMonitoring/Turquoise.Api.HealthMonitoring.sln   /p:CollectCoverage=true /p:CoverletOutput=/TestResults/ /p:MergeWith=/TestResults/coverage.json --logger=trx -r /TestResults/
RUN dotnet test ./Turquoise.Empty.Tests/Turquoise.Empty.Tests.sln /p:CollectCoverage=true /p:MergeWith="/TestResults/coverage.json" /p:CoverletOutputFormat="opencover" /p:CoverletOutput=/TestResults/

RUN dotnet build-server shutdown
RUN dotnet sonarscanner end /d:sonar.login=$SONARKEY

ENTRYPOINT dotnet test ./Turquoise.Api.HealthMonitoring/Turquoise.Api.HealthMonitoring.sln  /p:CollectCoverage=true /p:Exclude="[xunit.*.*]*" /p:CoverletOutput=/TestResults/ /p:MergeWith=/TestResults/coverage.json --logger=trx -r /TestResults/ && dotnet test ./Sentinel.Empty.Tests/Sentinel.Empty.Tests.sln /p:CollectCoverage=true /p:MergeWith="/TestResults/coverage.json" /p:CoverletOutputFormat="cobertura" /p:CoverletOutput=/TestResults/