version: "3.8"

services:
  turquoise-comms:
    image: mmercan/turquoise-comms:${TAGVersion}-prod-linux
    build:
      target: final
      context: ../../
      dockerfile: Workers/Turquoise.Worker.Comms/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    # ports:
    #   - "5005:80"
