version: "3.4"

services:
  turquoise-comms:
    image: turquoise-comms-test
    build:
      target: test
      context: ../../
      dockerfile: Workers/Turquoise.Worker.Comms/Dockerfile-test
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
