version: "3.8"

services:
  turquoise-scaler:
    image: mmercan/turquoise-scaler:${TAGVersion}-prod-linux
    build:
      target: final
      context: ../../
      dockerfile: Workers/Turquoise.Worker.Scaler/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    # ports:
    #   - "5005:80"
