apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: px-mongo-pvc
  #  annotations:
  #    volume.beta.kubernetes.io/storage-class: azurefile
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: turquoise-db-mongodb
  labels:
    app: turquoise-db-mongodb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: turquoise-db-mongodb
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: turquoise-db-mongodb
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: turquoise-db-mongodb
    spec:
      containers:
        - name: turquoise-db-mongodb
          image: mmercan/turquoise-db-mongodb
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_DATA_DIR
              value: "/data/db"
            - name: MONGO_LOG_DIR
              value: "/dev/null"
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "root"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "hbMnztmZ4w9JJTGZ"
      #   volumeMounts:
      #   - mountPath: /data/db
      #     name: mongodb
      # volumes:
      # - name: mongodb
      #   persistentVolumeClaim:
      #     claimName: px-mongo-pvc
