version: "3.4"

services:
  turquoise-handler-healthMonitoring:
    image: mmercan/turquoise-handler-healthMonitoring:${TAGVersion}-prod-linux
    build:
      target: final
      context: ../
      dockerfile: Turquoise.Handler.HealthMonitoring/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    # ports:
    #   - "5005:80"
