# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: |
      cd $(Build.SourcesDirectory)/HealthChecks/Turquoise.HealthChecks.Mongo
      dotnet --version

      dotnet restore
      dotnet build
      b="$(Build.SourceBranchName)"
      if ($b -eq "master") then
        dotnet pack --output $(Build.ArtifactStagingDirectory) --no-restore --version-suffix ci-$(Build.BuildNumber)
       else 
        dotnet pack --output $(Build.ArtifactStagingDirectory) --no-restore --version-suffix ci-$(Build.BuildNumber)
      fi
    displayName: "Run a multi-line script"

  - task: NuGetCommand@2
    inputs:
      command: "push"
      packagesToPush: "$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg"
      nuGetFeedType: "external"
      publishFeedCredentials: "nuget.org"
