apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "turquoise-k8s-reposync.fullname" . }}-config"
  labels:
    {{- include "turquoise-k8s-reposync.labels" . | nindent 4 }}
data:
 {{- if .Values.configmap -}}
{{- range $key, $value := .Values.configmap }}
 {{ $key }}: {{ default "" $value  | quote }}
{{- end -}}
{{- end }}


