apiVersion: v1
kind: Service
metadata:
  name: {{ include "Turquoise.Service.Rabbitmq.fullname" . }}-http
  labels:                    
    {{- include "Turquoise.Service.Rabbitmq.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http               
    port: 80               
    targetPort: 15672
    protocol: TCP            
  selector:
    {{- include "Turquoise.Service.Rabbitmq.selectorLabels" . | nindent 4 }}

