// source: K8sHealthcheck.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
goog.exportSymbol('proto.k8App.DeploymentListReply', null, global);
goog.exportSymbol('proto.k8App.DeploymentReply', null, global);
goog.exportSymbol('proto.k8App.GetDeploymentsRequest', null, global);
goog.exportSymbol('proto.k8App.GetServicesRequest', null, global);
goog.exportSymbol('proto.k8App.NamespaceListReply', null, global);
goog.exportSymbol('proto.k8App.NamespaceReply', null, global);
goog.exportSymbol('proto.k8App.Pair', null, global);
goog.exportSymbol('proto.k8App.ServiceListReply', null, global);
goog.exportSymbol('proto.k8App.ServiceReply', null, global);
goog.exportSymbol('proto.k8App.StringMessage', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.k8App.GetServicesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.k8App.GetServicesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.k8App.GetServicesRequest.displayName = 'proto.k8App.GetServicesRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.k8App.GetDeploymentsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.k8App.GetDeploymentsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.k8App.GetDeploymentsRequest.displayName = 'proto.k8App.GetDeploymentsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.k8App.NamespaceListReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.k8App.NamespaceListReply.repeatedFields_, null);
};
goog.inherits(proto.k8App.NamespaceListReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.k8App.NamespaceListReply.displayName = 'proto.k8App.NamespaceListReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.k8App.NamespaceReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.k8App.NamespaceReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.k8App.NamespaceReply.displayName = 'proto.k8App.NamespaceReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.k8App.DeploymentListReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.k8App.DeploymentListReply.repeatedFields_, null);
};
goog.inherits(proto.k8App.DeploymentListReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.k8App.DeploymentListReply.displayName = 'proto.k8App.DeploymentListReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.k8App.DeploymentReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.k8App.DeploymentReply.repeatedFields_, null);
};
goog.inherits(proto.k8App.DeploymentReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.k8App.DeploymentReply.displayName = 'proto.k8App.DeploymentReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.k8App.Pair = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.k8App.Pair, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.k8App.Pair.displayName = 'proto.k8App.Pair';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.k8App.StringMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.k8App.StringMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.k8App.StringMessage.displayName = 'proto.k8App.StringMessage';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.k8App.ServiceListReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.k8App.ServiceListReply.repeatedFields_, null);
};
goog.inherits(proto.k8App.ServiceListReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.k8App.ServiceListReply.displayName = 'proto.k8App.ServiceListReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.k8App.ServiceReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.k8App.ServiceReply.repeatedFields_, null);
};
goog.inherits(proto.k8App.ServiceReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.k8App.ServiceReply.displayName = 'proto.k8App.ServiceReply';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.k8App.GetServicesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.k8App.GetServicesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.k8App.GetServicesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8App.GetServicesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    namespaceparam: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.k8App.GetServicesRequest}
 */
proto.k8App.GetServicesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.k8App.GetServicesRequest;
  return proto.k8App.GetServicesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.k8App.GetServicesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.k8App.GetServicesRequest}
 */
proto.k8App.GetServicesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNamespaceparam(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.k8App.GetServicesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.k8App.GetServicesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.k8App.GetServicesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8App.GetServicesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNamespaceparam();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string NamespaceParam = 1;
 * @return {string}
 */
proto.k8App.GetServicesRequest.prototype.getNamespaceparam = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.k8App.GetServicesRequest} returns this
 */
proto.k8App.GetServicesRequest.prototype.setNamespaceparam = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.k8App.GetDeploymentsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.k8App.GetDeploymentsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.k8App.GetDeploymentsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8App.GetDeploymentsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    namespace: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.k8App.GetDeploymentsRequest}
 */
proto.k8App.GetDeploymentsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.k8App.GetDeploymentsRequest;
  return proto.k8App.GetDeploymentsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.k8App.GetDeploymentsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.k8App.GetDeploymentsRequest}
 */
proto.k8App.GetDeploymentsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNamespace(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.k8App.GetDeploymentsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.k8App.GetDeploymentsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.k8App.GetDeploymentsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8App.GetDeploymentsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNamespace();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string namespace = 1;
 * @return {string}
 */
proto.k8App.GetDeploymentsRequest.prototype.getNamespace = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.k8App.GetDeploymentsRequest} returns this
 */
proto.k8App.GetDeploymentsRequest.prototype.setNamespace = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.k8App.NamespaceListReply.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.k8App.NamespaceListReply.prototype.toObject = function(opt_includeInstance) {
  return proto.k8App.NamespaceListReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.k8App.NamespaceListReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8App.NamespaceListReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    namespacesList: jspb.Message.toObjectList(msg.getNamespacesList(),
    proto.k8App.NamespaceReply.toObject, includeInstance),
    updatedtime: (f = msg.getUpdatedtime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.k8App.NamespaceListReply}
 */
proto.k8App.NamespaceListReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.k8App.NamespaceListReply;
  return proto.k8App.NamespaceListReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.k8App.NamespaceListReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.k8App.NamespaceListReply}
 */
proto.k8App.NamespaceListReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.k8App.NamespaceReply;
      reader.readMessage(value,proto.k8App.NamespaceReply.deserializeBinaryFromReader);
      msg.addNamespaces(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedtime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.k8App.NamespaceListReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.k8App.NamespaceListReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.k8App.NamespaceListReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8App.NamespaceListReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNamespacesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.k8App.NamespaceReply.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedtime();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * repeated NamespaceReply namespaces = 1;
 * @return {!Array<!proto.k8App.NamespaceReply>}
 */
proto.k8App.NamespaceListReply.prototype.getNamespacesList = function() {
  return /** @type{!Array<!proto.k8App.NamespaceReply>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.k8App.NamespaceReply, 1));
};


/**
 * @param {!Array<!proto.k8App.NamespaceReply>} value
 * @return {!proto.k8App.NamespaceListReply} returns this
*/
proto.k8App.NamespaceListReply.prototype.setNamespacesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.k8App.NamespaceReply=} opt_value
 * @param {number=} opt_index
 * @return {!proto.k8App.NamespaceReply}
 */
proto.k8App.NamespaceListReply.prototype.addNamespaces = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.k8App.NamespaceReply, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.k8App.NamespaceListReply} returns this
 */
proto.k8App.NamespaceListReply.prototype.clearNamespacesList = function() {
  return this.setNamespacesList([]);
};


/**
 * optional google.protobuf.Timestamp UpdatedTime = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.k8App.NamespaceListReply.prototype.getUpdatedtime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.k8App.NamespaceListReply} returns this
*/
proto.k8App.NamespaceListReply.prototype.setUpdatedtime = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.k8App.NamespaceListReply} returns this
 */
proto.k8App.NamespaceListReply.prototype.clearUpdatedtime = function() {
  return this.setUpdatedtime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.k8App.NamespaceListReply.prototype.hasUpdatedtime = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.k8App.NamespaceReply.prototype.toObject = function(opt_includeInstance) {
  return proto.k8App.NamespaceReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.k8App.NamespaceReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8App.NamespaceReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    namespace: jspb.Message.getFieldWithDefault(msg, 1, ""),
    warning: jspb.Message.getFieldWithDefault(msg, 2, 0),
    errors: jspb.Message.getFieldWithDefault(msg, 3, 0),
    creationdate: (f = msg.getCreationdate()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.k8App.NamespaceReply}
 */
proto.k8App.NamespaceReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.k8App.NamespaceReply;
  return proto.k8App.NamespaceReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.k8App.NamespaceReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.k8App.NamespaceReply}
 */
proto.k8App.NamespaceReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNamespace(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setWarning(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setErrors(value);
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreationdate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.k8App.NamespaceReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.k8App.NamespaceReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.k8App.NamespaceReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8App.NamespaceReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNamespace();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getWarning();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getErrors();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getCreationdate();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string namespace = 1;
 * @return {string}
 */
proto.k8App.NamespaceReply.prototype.getNamespace = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.k8App.NamespaceReply} returns this
 */
proto.k8App.NamespaceReply.prototype.setNamespace = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 Warning = 2;
 * @return {number}
 */
proto.k8App.NamespaceReply.prototype.getWarning = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.k8App.NamespaceReply} returns this
 */
proto.k8App.NamespaceReply.prototype.setWarning = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 Errors = 3;
 * @return {number}
 */
proto.k8App.NamespaceReply.prototype.getErrors = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.k8App.NamespaceReply} returns this
 */
proto.k8App.NamespaceReply.prototype.setErrors = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional google.protobuf.Timestamp CreationDate = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.k8App.NamespaceReply.prototype.getCreationdate = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.k8App.NamespaceReply} returns this
*/
proto.k8App.NamespaceReply.prototype.setCreationdate = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.k8App.NamespaceReply} returns this
 */
proto.k8App.NamespaceReply.prototype.clearCreationdate = function() {
  return this.setCreationdate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.k8App.NamespaceReply.prototype.hasCreationdate = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.k8App.DeploymentListReply.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.k8App.DeploymentListReply.prototype.toObject = function(opt_includeInstance) {
  return proto.k8App.DeploymentListReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.k8App.DeploymentListReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8App.DeploymentListReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    deploymentsList: jspb.Message.toObjectList(msg.getDeploymentsList(),
    proto.k8App.DeploymentReply.toObject, includeInstance),
    updatedtime: (f = msg.getUpdatedtime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.k8App.DeploymentListReply}
 */
proto.k8App.DeploymentListReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.k8App.DeploymentListReply;
  return proto.k8App.DeploymentListReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.k8App.DeploymentListReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.k8App.DeploymentListReply}
 */
proto.k8App.DeploymentListReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.k8App.DeploymentReply;
      reader.readMessage(value,proto.k8App.DeploymentReply.deserializeBinaryFromReader);
      msg.addDeployments(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedtime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.k8App.DeploymentListReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.k8App.DeploymentListReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.k8App.DeploymentListReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8App.DeploymentListReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDeploymentsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.k8App.DeploymentReply.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedtime();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * repeated DeploymentReply deployments = 1;
 * @return {!Array<!proto.k8App.DeploymentReply>}
 */
proto.k8App.DeploymentListReply.prototype.getDeploymentsList = function() {
  return /** @type{!Array<!proto.k8App.DeploymentReply>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.k8App.DeploymentReply, 1));
};


/**
 * @param {!Array<!proto.k8App.DeploymentReply>} value
 * @return {!proto.k8App.DeploymentListReply} returns this
*/
proto.k8App.DeploymentListReply.prototype.setDeploymentsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.k8App.DeploymentReply=} opt_value
 * @param {number=} opt_index
 * @return {!proto.k8App.DeploymentReply}
 */
proto.k8App.DeploymentListReply.prototype.addDeployments = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.k8App.DeploymentReply, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.k8App.DeploymentListReply} returns this
 */
proto.k8App.DeploymentListReply.prototype.clearDeploymentsList = function() {
  return this.setDeploymentsList([]);
};


/**
 * optional google.protobuf.Timestamp UpdatedTime = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.k8App.DeploymentListReply.prototype.getUpdatedtime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.k8App.DeploymentListReply} returns this
*/
proto.k8App.DeploymentListReply.prototype.setUpdatedtime = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.k8App.DeploymentListReply} returns this
 */
proto.k8App.DeploymentListReply.prototype.clearUpdatedtime = function() {
  return this.setUpdatedtime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.k8App.DeploymentListReply.prototype.hasUpdatedtime = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.k8App.DeploymentReply.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.k8App.DeploymentReply.prototype.toObject = function(opt_includeInstance) {
  return proto.k8App.DeploymentReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.k8App.DeploymentReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8App.DeploymentReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    labelsList: jspb.Message.toObjectList(msg.getLabelsList(),
    proto.k8App.Pair.toObject, includeInstance),
    image: jspb.Message.getFieldWithDefault(msg, 3, ""),
    status: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.k8App.DeploymentReply}
 */
proto.k8App.DeploymentReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.k8App.DeploymentReply;
  return proto.k8App.DeploymentReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.k8App.DeploymentReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.k8App.DeploymentReply}
 */
proto.k8App.DeploymentReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = new proto.k8App.Pair;
      reader.readMessage(value,proto.k8App.Pair.deserializeBinaryFromReader);
      msg.addLabels(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setImage(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.k8App.DeploymentReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.k8App.DeploymentReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.k8App.DeploymentReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8App.DeploymentReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLabelsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.k8App.Pair.serializeBinaryToWriter
    );
  }
  f = message.getImage();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string Name = 1;
 * @return {string}
 */
proto.k8App.DeploymentReply.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.k8App.DeploymentReply} returns this
 */
proto.k8App.DeploymentReply.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated Pair Labels = 2;
 * @return {!Array<!proto.k8App.Pair>}
 */
proto.k8App.DeploymentReply.prototype.getLabelsList = function() {
  return /** @type{!Array<!proto.k8App.Pair>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.k8App.Pair, 2));
};


/**
 * @param {!Array<!proto.k8App.Pair>} value
 * @return {!proto.k8App.DeploymentReply} returns this
*/
proto.k8App.DeploymentReply.prototype.setLabelsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.k8App.Pair=} opt_value
 * @param {number=} opt_index
 * @return {!proto.k8App.Pair}
 */
proto.k8App.DeploymentReply.prototype.addLabels = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.k8App.Pair, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.k8App.DeploymentReply} returns this
 */
proto.k8App.DeploymentReply.prototype.clearLabelsList = function() {
  return this.setLabelsList([]);
};


/**
 * optional string Image = 3;
 * @return {string}
 */
proto.k8App.DeploymentReply.prototype.getImage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.k8App.DeploymentReply} returns this
 */
proto.k8App.DeploymentReply.prototype.setImage = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string status = 4;
 * @return {string}
 */
proto.k8App.DeploymentReply.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.k8App.DeploymentReply} returns this
 */
proto.k8App.DeploymentReply.prototype.setStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.k8App.Pair.prototype.toObject = function(opt_includeInstance) {
  return proto.k8App.Pair.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.k8App.Pair} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8App.Pair.toObject = function(includeInstance, msg) {
  var f, obj = {
    key: jspb.Message.getFieldWithDefault(msg, 1, ""),
    value: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.k8App.Pair}
 */
proto.k8App.Pair.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.k8App.Pair;
  return proto.k8App.Pair.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.k8App.Pair} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.k8App.Pair}
 */
proto.k8App.Pair.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.k8App.Pair.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.k8App.Pair.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.k8App.Pair} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8App.Pair.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getKey();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getValue();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string key = 1;
 * @return {string}
 */
proto.k8App.Pair.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.k8App.Pair} returns this
 */
proto.k8App.Pair.prototype.setKey = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string value = 2;
 * @return {string}
 */
proto.k8App.Pair.prototype.getValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.k8App.Pair} returns this
 */
proto.k8App.Pair.prototype.setValue = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.k8App.StringMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.k8App.StringMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.k8App.StringMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8App.StringMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    value: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.k8App.StringMessage}
 */
proto.k8App.StringMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.k8App.StringMessage;
  return proto.k8App.StringMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.k8App.StringMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.k8App.StringMessage}
 */
proto.k8App.StringMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.k8App.StringMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.k8App.StringMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.k8App.StringMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8App.StringMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValue();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string value = 1;
 * @return {string}
 */
proto.k8App.StringMessage.prototype.getValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.k8App.StringMessage} returns this
 */
proto.k8App.StringMessage.prototype.setValue = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.k8App.ServiceListReply.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.k8App.ServiceListReply.prototype.toObject = function(opt_includeInstance) {
  return proto.k8App.ServiceListReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.k8App.ServiceListReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8App.ServiceListReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    servicesList: jspb.Message.toObjectList(msg.getServicesList(),
    proto.k8App.ServiceReply.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.k8App.ServiceListReply}
 */
proto.k8App.ServiceListReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.k8App.ServiceListReply;
  return proto.k8App.ServiceListReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.k8App.ServiceListReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.k8App.ServiceListReply}
 */
proto.k8App.ServiceListReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.k8App.ServiceReply;
      reader.readMessage(value,proto.k8App.ServiceReply.deserializeBinaryFromReader);
      msg.addServices(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.k8App.ServiceListReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.k8App.ServiceListReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.k8App.ServiceListReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8App.ServiceListReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getServicesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.k8App.ServiceReply.serializeBinaryToWriter
    );
  }
};


/**
 * repeated ServiceReply Services = 1;
 * @return {!Array<!proto.k8App.ServiceReply>}
 */
proto.k8App.ServiceListReply.prototype.getServicesList = function() {
  return /** @type{!Array<!proto.k8App.ServiceReply>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.k8App.ServiceReply, 1));
};


/**
 * @param {!Array<!proto.k8App.ServiceReply>} value
 * @return {!proto.k8App.ServiceListReply} returns this
*/
proto.k8App.ServiceListReply.prototype.setServicesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.k8App.ServiceReply=} opt_value
 * @param {number=} opt_index
 * @return {!proto.k8App.ServiceReply}
 */
proto.k8App.ServiceListReply.prototype.addServices = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.k8App.ServiceReply, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.k8App.ServiceListReply} returns this
 */
proto.k8App.ServiceListReply.prototype.clearServicesList = function() {
  return this.setServicesList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.k8App.ServiceReply.repeatedFields_ = [5,7,8,12,13];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.k8App.ServiceReply.prototype.toObject = function(opt_includeInstance) {
  return proto.k8App.ServiceReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.k8App.ServiceReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8App.ServiceReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    nameandnamespace: jspb.Message.getFieldWithDefault(msg, 1, ""),
    uid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    name: jspb.Message.getFieldWithDefault(msg, 33, ""),
    namespace: jspb.Message.getFieldWithDefault(msg, 4, ""),
    labelsList: jspb.Message.toObjectList(msg.getLabelsList(),
    proto.k8App.Pair.toObject, includeInstance),
    creationtime: (f = msg.getCreationtime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    labelselectorList: jspb.Message.toObjectList(msg.getLabelselectorList(),
    proto.k8App.Pair.toObject, includeInstance),
    annotationsList: jspb.Message.toObjectList(msg.getAnnotationsList(),
    proto.k8App.Pair.toObject, includeInstance),
    servicetype: jspb.Message.getFieldWithDefault(msg, 9, ""),
    sessionaffinity: jspb.Message.getFieldWithDefault(msg, 10, ""),
    clusterip: jspb.Message.getFieldWithDefault(msg, 11, ""),
    internalendpointsList: jspb.Message.toObjectList(msg.getInternalendpointsList(),
    proto.k8App.StringMessage.toObject, includeInstance),
    externalendpointsList: jspb.Message.toObjectList(msg.getExternalendpointsList(),
    proto.k8App.StringMessage.toObject, includeInstance),
    ingressurl: jspb.Message.getFieldWithDefault(msg, 14, ""),
    virtualserviceurl: jspb.Message.getFieldWithDefault(msg, 15, ""),
    latestsyncdateutc: (f = msg.getLatestsyncdateutc()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    deleted: jspb.Message.getBooleanFieldWithDefault(msg, 17, false),
    healthisalive: jspb.Message.getFieldWithDefault(msg, 18, ""),
    healthisalivesyncdateutc: (f = msg.getHealthisalivesyncdateutc()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    healthisaliveandwell: jspb.Message.getFieldWithDefault(msg, 21, ""),
    healthisaliveandwellsyncdateutc: (f = msg.getHealthisaliveandwellsyncdateutc()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.k8App.ServiceReply}
 */
proto.k8App.ServiceReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.k8App.ServiceReply;
  return proto.k8App.ServiceReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.k8App.ServiceReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.k8App.ServiceReply}
 */
proto.k8App.ServiceReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNameandnamespace(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUid(value);
      break;
    case 33:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setNamespace(value);
      break;
    case 5:
      var value = new proto.k8App.Pair;
      reader.readMessage(value,proto.k8App.Pair.deserializeBinaryFromReader);
      msg.addLabels(value);
      break;
    case 6:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreationtime(value);
      break;
    case 7:
      var value = new proto.k8App.Pair;
      reader.readMessage(value,proto.k8App.Pair.deserializeBinaryFromReader);
      msg.addLabelselector(value);
      break;
    case 8:
      var value = new proto.k8App.Pair;
      reader.readMessage(value,proto.k8App.Pair.deserializeBinaryFromReader);
      msg.addAnnotations(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setServicetype(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setSessionaffinity(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setClusterip(value);
      break;
    case 12:
      var value = new proto.k8App.StringMessage;
      reader.readMessage(value,proto.k8App.StringMessage.deserializeBinaryFromReader);
      msg.addInternalendpoints(value);
      break;
    case 13:
      var value = new proto.k8App.StringMessage;
      reader.readMessage(value,proto.k8App.StringMessage.deserializeBinaryFromReader);
      msg.addExternalendpoints(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setIngressurl(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setVirtualserviceurl(value);
      break;
    case 16:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setLatestsyncdateutc(value);
      break;
    case 17:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDeleted(value);
      break;
    case 18:
      var value = /** @type {string} */ (reader.readString());
      msg.setHealthisalive(value);
      break;
    case 20:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setHealthisalivesyncdateutc(value);
      break;
    case 21:
      var value = /** @type {string} */ (reader.readString());
      msg.setHealthisaliveandwell(value);
      break;
    case 22:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setHealthisaliveandwellsyncdateutc(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.k8App.ServiceReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.k8App.ServiceReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.k8App.ServiceReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8App.ServiceReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNameandnamespace();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      33,
      f
    );
  }
  f = message.getNamespace();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getLabelsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.k8App.Pair.serializeBinaryToWriter
    );
  }
  f = message.getCreationtime();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getLabelselectorList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      proto.k8App.Pair.serializeBinaryToWriter
    );
  }
  f = message.getAnnotationsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      proto.k8App.Pair.serializeBinaryToWriter
    );
  }
  f = message.getServicetype();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getSessionaffinity();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getClusterip();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getInternalendpointsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      12,
      f,
      proto.k8App.StringMessage.serializeBinaryToWriter
    );
  }
  f = message.getExternalendpointsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      13,
      f,
      proto.k8App.StringMessage.serializeBinaryToWriter
    );
  }
  f = message.getIngressurl();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getVirtualserviceurl();
  if (f.length > 0) {
    writer.writeString(
      15,
      f
    );
  }
  f = message.getLatestsyncdateutc();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getDeleted();
  if (f) {
    writer.writeBool(
      17,
      f
    );
  }
  f = message.getHealthisalive();
  if (f.length > 0) {
    writer.writeString(
      18,
      f
    );
  }
  f = message.getHealthisalivesyncdateutc();
  if (f != null) {
    writer.writeMessage(
      20,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getHealthisaliveandwell();
  if (f.length > 0) {
    writer.writeString(
      21,
      f
    );
  }
  f = message.getHealthisaliveandwellsyncdateutc();
  if (f != null) {
    writer.writeMessage(
      22,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string NameandNamespace = 1;
 * @return {string}
 */
proto.k8App.ServiceReply.prototype.getNameandnamespace = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.k8App.ServiceReply} returns this
 */
proto.k8App.ServiceReply.prototype.setNameandnamespace = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string Uid = 2;
 * @return {string}
 */
proto.k8App.ServiceReply.prototype.getUid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.k8App.ServiceReply} returns this
 */
proto.k8App.ServiceReply.prototype.setUid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string Name = 33;
 * @return {string}
 */
proto.k8App.ServiceReply.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 33, ""));
};


/**
 * @param {string} value
 * @return {!proto.k8App.ServiceReply} returns this
 */
proto.k8App.ServiceReply.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 33, value);
};


/**
 * optional string Namespace = 4;
 * @return {string}
 */
proto.k8App.ServiceReply.prototype.getNamespace = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.k8App.ServiceReply} returns this
 */
proto.k8App.ServiceReply.prototype.setNamespace = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * repeated Pair Labels = 5;
 * @return {!Array<!proto.k8App.Pair>}
 */
proto.k8App.ServiceReply.prototype.getLabelsList = function() {
  return /** @type{!Array<!proto.k8App.Pair>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.k8App.Pair, 5));
};


/**
 * @param {!Array<!proto.k8App.Pair>} value
 * @return {!proto.k8App.ServiceReply} returns this
*/
proto.k8App.ServiceReply.prototype.setLabelsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.k8App.Pair=} opt_value
 * @param {number=} opt_index
 * @return {!proto.k8App.Pair}
 */
proto.k8App.ServiceReply.prototype.addLabels = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.k8App.Pair, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.k8App.ServiceReply} returns this
 */
proto.k8App.ServiceReply.prototype.clearLabelsList = function() {
  return this.setLabelsList([]);
};


/**
 * optional google.protobuf.Timestamp CreationTime = 6;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.k8App.ServiceReply.prototype.getCreationtime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 6));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.k8App.ServiceReply} returns this
*/
proto.k8App.ServiceReply.prototype.setCreationtime = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.k8App.ServiceReply} returns this
 */
proto.k8App.ServiceReply.prototype.clearCreationtime = function() {
  return this.setCreationtime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.k8App.ServiceReply.prototype.hasCreationtime = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * repeated Pair LabelSelector = 7;
 * @return {!Array<!proto.k8App.Pair>}
 */
proto.k8App.ServiceReply.prototype.getLabelselectorList = function() {
  return /** @type{!Array<!proto.k8App.Pair>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.k8App.Pair, 7));
};


/**
 * @param {!Array<!proto.k8App.Pair>} value
 * @return {!proto.k8App.ServiceReply} returns this
*/
proto.k8App.ServiceReply.prototype.setLabelselectorList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.k8App.Pair=} opt_value
 * @param {number=} opt_index
 * @return {!proto.k8App.Pair}
 */
proto.k8App.ServiceReply.prototype.addLabelselector = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.k8App.Pair, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.k8App.ServiceReply} returns this
 */
proto.k8App.ServiceReply.prototype.clearLabelselectorList = function() {
  return this.setLabelselectorList([]);
};


/**
 * repeated Pair Annotations = 8;
 * @return {!Array<!proto.k8App.Pair>}
 */
proto.k8App.ServiceReply.prototype.getAnnotationsList = function() {
  return /** @type{!Array<!proto.k8App.Pair>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.k8App.Pair, 8));
};


/**
 * @param {!Array<!proto.k8App.Pair>} value
 * @return {!proto.k8App.ServiceReply} returns this
*/
proto.k8App.ServiceReply.prototype.setAnnotationsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.k8App.Pair=} opt_value
 * @param {number=} opt_index
 * @return {!proto.k8App.Pair}
 */
proto.k8App.ServiceReply.prototype.addAnnotations = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.k8App.Pair, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.k8App.ServiceReply} returns this
 */
proto.k8App.ServiceReply.prototype.clearAnnotationsList = function() {
  return this.setAnnotationsList([]);
};


/**
 * optional string ServiceType = 9;
 * @return {string}
 */
proto.k8App.ServiceReply.prototype.getServicetype = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.k8App.ServiceReply} returns this
 */
proto.k8App.ServiceReply.prototype.setServicetype = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string SessionAffinity = 10;
 * @return {string}
 */
proto.k8App.ServiceReply.prototype.getSessionaffinity = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.k8App.ServiceReply} returns this
 */
proto.k8App.ServiceReply.prototype.setSessionaffinity = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string clusterIP = 11;
 * @return {string}
 */
proto.k8App.ServiceReply.prototype.getClusterip = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.k8App.ServiceReply} returns this
 */
proto.k8App.ServiceReply.prototype.setClusterip = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * repeated StringMessage internalEndpoints = 12;
 * @return {!Array<!proto.k8App.StringMessage>}
 */
proto.k8App.ServiceReply.prototype.getInternalendpointsList = function() {
  return /** @type{!Array<!proto.k8App.StringMessage>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.k8App.StringMessage, 12));
};


/**
 * @param {!Array<!proto.k8App.StringMessage>} value
 * @return {!proto.k8App.ServiceReply} returns this
*/
proto.k8App.ServiceReply.prototype.setInternalendpointsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 12, value);
};


/**
 * @param {!proto.k8App.StringMessage=} opt_value
 * @param {number=} opt_index
 * @return {!proto.k8App.StringMessage}
 */
proto.k8App.ServiceReply.prototype.addInternalendpoints = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 12, opt_value, proto.k8App.StringMessage, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.k8App.ServiceReply} returns this
 */
proto.k8App.ServiceReply.prototype.clearInternalendpointsList = function() {
  return this.setInternalendpointsList([]);
};


/**
 * repeated StringMessage externalEndpoints = 13;
 * @return {!Array<!proto.k8App.StringMessage>}
 */
proto.k8App.ServiceReply.prototype.getExternalendpointsList = function() {
  return /** @type{!Array<!proto.k8App.StringMessage>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.k8App.StringMessage, 13));
};


/**
 * @param {!Array<!proto.k8App.StringMessage>} value
 * @return {!proto.k8App.ServiceReply} returns this
*/
proto.k8App.ServiceReply.prototype.setExternalendpointsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 13, value);
};


/**
 * @param {!proto.k8App.StringMessage=} opt_value
 * @param {number=} opt_index
 * @return {!proto.k8App.StringMessage}
 */
proto.k8App.ServiceReply.prototype.addExternalendpoints = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 13, opt_value, proto.k8App.StringMessage, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.k8App.ServiceReply} returns this
 */
proto.k8App.ServiceReply.prototype.clearExternalendpointsList = function() {
  return this.setExternalendpointsList([]);
};


/**
 * optional string IngressUrl = 14;
 * @return {string}
 */
proto.k8App.ServiceReply.prototype.getIngressurl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.k8App.ServiceReply} returns this
 */
proto.k8App.ServiceReply.prototype.setIngressurl = function(value) {
  return jspb.Message.setProto3StringField(this, 14, value);
};


/**
 * optional string VirtualServiceUrl = 15;
 * @return {string}
 */
proto.k8App.ServiceReply.prototype.getVirtualserviceurl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/**
 * @param {string} value
 * @return {!proto.k8App.ServiceReply} returns this
 */
proto.k8App.ServiceReply.prototype.setVirtualserviceurl = function(value) {
  return jspb.Message.setProto3StringField(this, 15, value);
};


/**
 * optional google.protobuf.Timestamp LatestSyncDateUTC = 16;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.k8App.ServiceReply.prototype.getLatestsyncdateutc = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 16));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.k8App.ServiceReply} returns this
*/
proto.k8App.ServiceReply.prototype.setLatestsyncdateutc = function(value) {
  return jspb.Message.setWrapperField(this, 16, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.k8App.ServiceReply} returns this
 */
proto.k8App.ServiceReply.prototype.clearLatestsyncdateutc = function() {
  return this.setLatestsyncdateutc(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.k8App.ServiceReply.prototype.hasLatestsyncdateutc = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional bool Deleted = 17;
 * @return {boolean}
 */
proto.k8App.ServiceReply.prototype.getDeleted = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 17, false));
};


/**
 * @param {boolean} value
 * @return {!proto.k8App.ServiceReply} returns this
 */
proto.k8App.ServiceReply.prototype.setDeleted = function(value) {
  return jspb.Message.setProto3BooleanField(this, 17, value);
};


/**
 * optional string HealthIsalive = 18;
 * @return {string}
 */
proto.k8App.ServiceReply.prototype.getHealthisalive = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 18, ""));
};


/**
 * @param {string} value
 * @return {!proto.k8App.ServiceReply} returns this
 */
proto.k8App.ServiceReply.prototype.setHealthisalive = function(value) {
  return jspb.Message.setProto3StringField(this, 18, value);
};


/**
 * optional google.protobuf.Timestamp healthIsaliveSyncDateUTC = 20;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.k8App.ServiceReply.prototype.getHealthisalivesyncdateutc = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 20));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.k8App.ServiceReply} returns this
*/
proto.k8App.ServiceReply.prototype.setHealthisalivesyncdateutc = function(value) {
  return jspb.Message.setWrapperField(this, 20, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.k8App.ServiceReply} returns this
 */
proto.k8App.ServiceReply.prototype.clearHealthisalivesyncdateutc = function() {
  return this.setHealthisalivesyncdateutc(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.k8App.ServiceReply.prototype.hasHealthisalivesyncdateutc = function() {
  return jspb.Message.getField(this, 20) != null;
};


/**
 * optional string healthIsaliveAndWell = 21;
 * @return {string}
 */
proto.k8App.ServiceReply.prototype.getHealthisaliveandwell = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 21, ""));
};


/**
 * @param {string} value
 * @return {!proto.k8App.ServiceReply} returns this
 */
proto.k8App.ServiceReply.prototype.setHealthisaliveandwell = function(value) {
  return jspb.Message.setProto3StringField(this, 21, value);
};


/**
 * optional google.protobuf.Timestamp healthIsaliveAndWellSyncDateUTC = 22;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.k8App.ServiceReply.prototype.getHealthisaliveandwellsyncdateutc = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 22));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.k8App.ServiceReply} returns this
*/
proto.k8App.ServiceReply.prototype.setHealthisaliveandwellsyncdateutc = function(value) {
  return jspb.Message.setWrapperField(this, 22, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.k8App.ServiceReply} returns this
 */
proto.k8App.ServiceReply.prototype.clearHealthisaliveandwellsyncdateutc = function() {
  return this.setHealthisaliveandwellsyncdateutc(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.k8App.ServiceReply.prototype.hasHealthisaliveandwellsyncdateutc = function() {
  return jspb.Message.getField(this, 22) != null;
};


goog.object.extend(exports, proto.k8App);
