{{- if .Values.configmap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "Turquoise.sync.fullname" . }}-config"
  labels:
    {{- include "Turquoise.sync.labels" . | nindent 4 }}
data:
 {{- if .Values.configmap -}}
{{- range $key, $value := .Values.configmap }}
 {{ $key }}: {{ default "" $value  | quote }}
{{- end -}}
{{- end }}

{{- end }}

