version: "3.8"

services:
  turquoise-healthchecker:
    image: mmercan/turquoise-healthchecker:${TAGVersion}-prod-linux
    build:
      target: final
      context: ../../
      dockerfile: WorkersTurquoise.Worker.HealthChecker/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    # ports:
    #   - "5005:80"
