version: "3.4"

services:
  turquoise-healthchecker:
    image: turquoise-healthchecker-test
    build:
      target: test
      context: ../../
      dockerfile: Workers/Turquoise.Worker.HealthChecker/Dockerfile-test
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
