version: "3.4"

services:
  turquoise-db-redis:
    image: mmercan/turquoise-db-redis:${TAGVersion}-prod-linux
    build:
      context: ./
      dockerfile: dockerfile
    hostname: redis
    ports:
      - "6379:6379"
