apiVersion: v1
kind: Service
metadata:
  name: turquoise-db-redis
  labels:
    app: turquoise-db-redis
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app: turquoise-db-redis
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: turquoise-db-redis
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: turquoise-db-redis
    spec:
      containers:
        - name: turquoise-db-redis
          image: mmercan/turquoise-db-redis
          ports:
            - containerPort: 6379
