version: "3.4"

services:
  turquoise-sync:
    image: turquoise-sync-test
    build:
      target: test
      context: ../../
      dockerfile: Workers/Turquoise.Worker.Sync/Dockerfile-test
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
